[project]
name = "ingestion"
version = "0.1.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "dlt[motherduck]>=0.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

