[project]
name = "transformations_dbt"
version = "0.1.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "dbt-core>=1.10.15",
    "dbt-duckdb>=1.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

